name: CI

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SERVER_USERNAME }}
          host: ${{ secrets.SERVER_IP }}
          key: ${{ secrets.SERVER_KEY }}
          script: sh ${{ secrets.SERVER_DEPLOY_SCRIPT_PATH }}